TILES = [
    'Brown Block',
    'Character Boy',
    'Character Cat Girl',
    'Character Horn Girl',
    'Character Pink Girl',
    'Character Princess Girl',
    'Chest Closed',
    'Chest Lid',
    'Chest Open',
    'Dirt Block',
    'Door Tall Closed',
    'Door Tall Open',
    'Enemy Bug',
    'Gem Blue',
    'Gem Green',
    'Gem Orange',
    'Grass Block',
    'Heart',
    'Key',
    'Plain Block',
    'Ramp East',
    'Ramp North',
    'Ramp South',
    'Ramp West',
    'Rock',
    'Roof East',
    'Roof North East',
    'Roof North West',
    'Roof North',
    'Roof South East',
    'Roof South West',
    'Roof South',
    'Roof West',
    'Selector',
    'Shadow East',
    'Shadow North East',
    'Shadow North West',
    'Shadow North',
    'Shadow Side West',
    'Shadow South East',
    'Shadow South West',
    'Shadow South',
    'Shadow West',
    'SpeechBubble',
    'Star',
    'Stone Block Tall',
    'Stone Block',
    'Tree Short',
    'Tree Tall',
    'Tree Ugly',
    'Wall Block Tall',
    'Wall Block',
    'Water Block',
    'Window Tall',
    'Wood Block',
]
